In [1]:
import numpy as np
import pandas as pd

from pathlib import Path
from scipy.io import loadmat

In [2]:
data_path = Path("../../datasets/SAM40/filtered_data")

files = sorted(data_path.glob("*.mat"))

print("Total files:", len(files))
print("\nFirst 5 files:")

for f in files[:5]:
    print(f.name)

Total files: 480

First 5 files:
Arithmetic_sub_10_trial1.mat
Arithmetic_sub_10_trial2.mat
Arithmetic_sub_10_trial3.mat
Arithmetic_sub_11_trial1.mat
Arithmetic_sub_11_trial2.mat

In [6]:
for file in files:
    try:
        parts = file.stem.split("_")

        subject = int(parts[2])
        trial = int(parts[3].replace("trial", ""))

    except Exception:
        print(file.name)

Mirror_image_sub_10_trial1.mat
Mirror_image_sub_10_trial2.mat
Mirror_image_sub_10_trial3.mat
Mirror_image_sub_11_trial1.mat
Mirror_image_sub_11_trial2.mat
Mirror_image_sub_11_trial3.mat
Mirror_image_sub_12_trial1.mat
Mirror_image_sub_12_trial2.mat
Mirror_image_sub_12_trial3.mat
Mirror_image_sub_13_trial1.mat
Mirror_image_sub_13_trial2.mat
Mirror_image_sub_13_trial3.mat
Mirror_image_sub_14_trial1.mat
Mirror_image_sub_14_trial2.mat
Mirror_image_sub_14_trial3.mat
Mirror_image_sub_15_trial1.mat
Mirror_image_sub_15_trial2.mat
Mirror_image_sub_15_trial3.mat
Mirror_image_sub_16_trial1.mat
Mirror_image_sub_16_trial2.mat
Mirror_image_sub_16_trial3.mat
Mirror_image_sub_17_trial1.mat
Mirror_image_sub_17_trial2.mat
Mirror_image_sub_17_trial3.mat
Mirror_image_sub_18_trial1.mat
Mirror_image_sub_18_trial2.mat
Mirror_image_sub_18_trial3.mat
Mirror_image_sub_19_trial1.mat
Mirror_image_sub_19_trial2.mat
Mirror_image_sub_19_trial3.mat
Mirror_image_sub_1_trial1.mat
Mirror_image_sub_1_trial2.mat
Mirror_image_sub_1_trial3.mat
Mirror_image_sub_20_trial1.mat
Mirror_image_sub_20_trial2.mat
Mirror_image_sub_20_trial3.mat
Mirror_image_sub_21_trial1.mat
Mirror_image_sub_21_trial2.mat
Mirror_image_sub_21_trial3.mat
Mirror_image_sub_22_trial1.mat
Mirror_image_sub_22_trial2.mat
Mirror_image_sub_22_trial3.mat
Mirror_image_sub_23_trial1.mat
Mirror_image_sub_23_trial2.mat
Mirror_image_sub_23_trial3.mat
Mirror_image_sub_24_trial1.mat
Mirror_image_sub_24_trial2.mat
Mirror_image_sub_24_trial3.mat
Mirror_image_sub_25_trial1.mat
Mirror_image_sub_25_trial2.mat
Mirror_image_sub_25_trial3.mat
Mirror_image_sub_26_trial1.mat
Mirror_image_sub_26_trial2.mat
Mirror_image_sub_26_trial3.mat
Mirror_image_sub_27_trial1.mat
Mirror_image_sub_27_trial2.mat
Mirror_image_sub_27_trial3.mat
Mirror_image_sub_28_trial1.mat
Mirror_image_sub_28_trial2.mat
Mirror_image_sub_28_trial3.mat
Mirror_image_sub_29_trial1.mat
Mirror_image_sub_29_trial2.mat
Mirror_image_sub_29_trial3.mat
Mirror_image_sub_2_trial1.mat
Mirror_image_sub_2_trial2.mat
Mirror_image_sub_2_trial3.mat
Mirror_image_sub_30_trial1.mat
Mirror_image_sub_30_trial2.mat
Mirror_image_sub_30_trial3.mat
Mirror_image_sub_31_trial1.mat
Mirror_image_sub_31_trial2.mat
Mirror_image_sub_31_trial3.mat
Mirror_image_sub_32_trial1.mat
Mirror_image_sub_32_trial2.mat
Mirror_image_sub_32_trial3.mat
Mirror_image_sub_33_trial1.mat
Mirror_image_sub_33_trial2.mat
Mirror_image_sub_33_trial3.mat
Mirror_image_sub_34_trial1.mat
Mirror_image_sub_34_trial2.mat
Mirror_image_sub_34_trial3.mat
Mirror_image_sub_35_trial1.mat
Mirror_image_sub_35_trial2.mat
Mirror_image_sub_35_trial3.mat
Mirror_image_sub_36_trial1.mat
Mirror_image_sub_36_trial2.mat
Mirror_image_sub_36_trial3.mat
Mirror_image_sub_37_trial1.mat
Mirror_image_sub_37_trial2.mat
Mirror_image_sub_37_trial3.mat
Mirror_image_sub_38_trial1.mat
Mirror_image_sub_38_trial2.mat
Mirror_image_sub_38_trial3.mat
Mirror_image_sub_39_trial1.mat
Mirror_image_sub_39_trial2.mat
Mirror_image_sub_39_trial3.mat
Mirror_image_sub_3_trial1.mat
Mirror_image_sub_3_trial2.mat
Mirror_image_sub_3_trial3.mat
Mirror_image_sub_40_trial1.mat
Mirror_image_sub_40_trial2.mat
Mirror_image_sub_40_trial3.mat
Mirror_image_sub_4_trial1.mat
Mirror_image_sub_4_trial2.mat
Mirror_image_sub_4_trial3.mat
Mirror_image_sub_5_trial1.mat
Mirror_image_sub_5_trial2.mat
Mirror_image_sub_5_trial3.mat
Mirror_image_sub_6_trial1.mat
Mirror_image_sub_6_trial2.mat
Mirror_image_sub_6_trial3.mat
Mirror_image_sub_7_trial1.mat
Mirror_image_sub_7_trial2.mat
Mirror_image_sub_7_trial3.mat
Mirror_image_sub_8_trial1.mat
Mirror_image_sub_8_trial2.mat
Mirror_image_sub_8_trial3.mat
Mirror_image_sub_9_trial1.mat
Mirror_image_sub_9_trial2.mat
Mirror_image_sub_9_trial3.mat

In [9]:
for file in files[:20]:
    print(file.name)

Arithmetic_sub_10_trial1.mat
Arithmetic_sub_10_trial2.mat
Arithmetic_sub_10_trial3.mat
Arithmetic_sub_11_trial1.mat
Arithmetic_sub_11_trial2.mat
Arithmetic_sub_11_trial3.mat
Arithmetic_sub_12_trial1.mat
Arithmetic_sub_12_trial2.mat
Arithmetic_sub_12_trial3.mat
Arithmetic_sub_13_trial1.mat
Arithmetic_sub_13_trial2.mat
Arithmetic_sub_13_trial3.mat
Arithmetic_sub_14_trial1.mat
Arithmetic_sub_14_trial2.mat
Arithmetic_sub_14_trial3.mat
Arithmetic_sub_15_trial1.mat
Arithmetic_sub_15_trial2.mat
Arithmetic_sub_15_trial3.mat
Arithmetic_sub_16_trial1.mat
Arithmetic_sub_16_trial2.mat

In [10]:
metadata = []

for file in files:

    parts = file.stem.split("_")

    subject_idx = parts.index("sub")

    task = "_".join(parts[:subject_idx])

    subject = int(parts[subject_idx + 1])

    trial = int(
        parts[subject_idx + 2].replace("trial", "")
    )

    metadata.append({
        "file": file.name,
        "task": task,
        "subject": subject,
        "trial": trial
    })

metadata_df = pd.DataFrame(metadata)

print(metadata_df.shape)
metadata_df.head()

(480, 4)

                           file        task  subject  trial
0  Arithmetic_sub_10_trial1.mat  Arithmetic       10      1
1  Arithmetic_sub_10_trial2.mat  Arithmetic       10      2
2  Arithmetic_sub_10_trial3.mat  Arithmetic       10      3
3  Arithmetic_sub_11_trial1.mat  Arithmetic       11      1
4  Arithmetic_sub_11_trial2.mat  Arithmetic       11      2

In [11]:
print(metadata_df["task"].value_counts())

task
Arithmetic      120
Mirror_image    120
Relax           120
Stroop          120
Name: count, dtype: int64

In [12]:
import pandas as pd

scores = pd.read_excel(
    "../../datasets/SAM40/scales.xls",
    header=None
)

scores

,0,1,2,3,4,5,6,7,8,9
0,Subject No.,Trial_1,NaN,NaN,Trial_2,NaN,NaN,Trial_3,NaN,NaN
1,NaN,Maths,Symmetry,Stroop,Maths,Symmetry,Stroop,Maths,Symmetry,Stroop
2,1,6,3,3,7,5,2,4,7,4
3,2,3,4,5,3,4,4,7,5,3
4,3,5,3,4,3,5,5,8,7,5
5,4,5,3,4,3,5,2,7,5,5
6,5,6,6,6,5,3,2,5,7,3
7,6,5,4,2,4,3,3,8,6,5
8,7,5,5,4,3,3,3,6,3,6
9,8,3,5,4,6,6,3,5,6,3
10,9,3,6,4,4,4,4,7,4,6
11,10,3,4,4,4,5,3,6,4,5
12,11,7,3,4,6,5,5,5,6,5
13,12,5,7,2,5,4,5,8,6,3
14,13,3,5,3,3,4,2,3,5,1
15,14,3,4,3,6,4,2,6,3,4
16,15,9,6,5,7,5,3,6,5,5
17,16,4,4,1,5,6,1,8,5,6
18,17,8,9,8,6,8,4,7,7,6
19,18,6,5,6,5,6,5,9,6,7
20,19,4,6,6,2,4,3,4,1,3
21,20,10,9,7,10,9,5,10,8,6
22,21,7,8,9,8,8,9,7,8,9
23,22,9,8,5,8,8,6,7,6,5
24,23,3,2,1,4,2,1,8,4,5
25,24,4,2,1,2,1,1,5,7,4
26,25,2,1,2,2,1,2,5,7,5
27,26,6,7,8,6,8,7,4,5,6
28,27,5,5,3,3,4,2,5,3,3
29,28,7,8,7,7,7,5,6,5,4
30,29,6,7,6,8,7,6,6,6,5
31,30,7,6,5,8,6,5,7,5,4
32,31,10,8,4,9,7,3,6,3,7
33,32,5,5,1,1,2,1,7,6,3
34,33,5,4,3,3,2,2,8,3,6
35,34,2,3,1,3,1,1,2,2,3
36,35,6,5,1,5,2,1,4,6,5
37,36,4,4,6,5,4,3,5,5,5
38,37,6,5,4,5,3,2,8,4,6
39,38,6,4,5,5,6,3,4,5,3
40,39,6,4,3,5,5,3,6,3,5
41,40,3,5,5,4,6,5,4,4,3

In [13]:
scores.shape

(42, 10)

In [14]:
labels = []

for _, row in scores.iloc[2:].iterrows():

    subject = int(row[0])

    # Trial 1
    labels.append({
        "subject": subject,
        "trial": 1,
        "task": "Arithmetic",
        "stress_score": row[1]
    })

    labels.append({
        "subject": subject,
        "trial": 1,
        "task": "Mirror_image",
        "stress_score": row[2]
    })

    labels.append({
        "subject": subject,
        "trial": 1,
        "task": "Stroop",
        "stress_score": row[3]
    })

    # Trial 2
    labels.append({
        "subject": subject,
        "trial": 2,
        "task": "Arithmetic",
        "stress_score": row[4]
    })

    labels.append({
        "subject": subject,
        "trial": 2,
        "task": "Mirror_image",
        "stress_score": row[5]
    })

    labels.append({
        "subject": subject,
        "trial": 2,
        "task": "Stroop",
        "stress_score": row[6]
    })

    # Trial 3
    labels.append({
        "subject": subject,
        "trial": 3,
        "task": "Arithmetic",
        "stress_score": row[7]
    })

    labels.append({
        "subject": subject,
        "trial": 3,
        "task": "Mirror_image",
        "stress_score": row[8]
    })

    labels.append({
        "subject": subject,
        "trial": 3,
        "task": "Stroop",
        "stress_score": row[9]
    })

labels_df = pd.DataFrame(labels)

print(labels_df.shape)
labels_df.head(10)

(360, 4)

   subject  trial          task  stress_score
0        1      1    Arithmetic             6
1        1      1  Mirror_image             3
2        1      1        Stroop             3
3        1      2    Arithmetic             7
4        1      2  Mirror_image             5
5        1      2        Stroop             2
6        1      3    Arithmetic             4
7        1      3  Mirror_image             7
8        1      3        Stroop             4
9        2      1    Arithmetic             3

In [15]:
print(labels_df.shape)
labels_df.head()

(360, 4)

   subject  trial          task  stress_score
0        1      1    Arithmetic             6
1        1      1  Mirror_image             3
2        1      1        Stroop             3
3        1      2    Arithmetic             7
4        1      2  Mirror_image             5

In [16]:
dataset_df = metadata_df.merge(
    labels_df,
    on=["subject", "trial", "task"],
    how="inner"
)

print(dataset_df.shape)

dataset_df.head()

(360, 5)

                           file        task  subject  trial  stress_score
0  Arithmetic_sub_10_trial1.mat  Arithmetic       10      1             3
1  Arithmetic_sub_10_trial2.mat  Arithmetic       10      2             4
2  Arithmetic_sub_10_trial3.mat  Arithmetic       10      3             6
3  Arithmetic_sub_11_trial1.mat  Arithmetic       11      1             7
4  Arithmetic_sub_11_trial2.mat  Arithmetic       11      2             6

In [17]:
dataset_df["stress_score"].describe()

count    360.000000
mean       4.811111
std        2.018822
min        1.000000
25%        3.000000
50%        5.000000
75%        6.000000
max       10.000000
Name: stress_score, dtype: float64

In [18]:
from scipy.io import loadmat

sample_file = files[0]

eeg = loadmat(sample_file)["Clean_data"]

print(eeg.shape)

(32, 3200)

In [19]:
import numpy as np

features = []

for ch in eeg:
    mean = np.mean(ch)
    std = np.std(ch)
    var = np.var(ch)
    rms = np.sqrt(np.mean(ch**2))

    features.extend([mean, std, var, rms])

print("Number of features:", len(features))
print(features[:10])

Number of features: 128
[np.float64(-0.07465654760599798), np.float64(6.740790629525689), np.float64(45.438258311101336), np.float64(6.741204040169811), np.float64(-0.04528717972682448), np.float64(6.253515868304656), np.float64(39.106460715138134), np.float64(6.253679848200237), np.float64(-0.029642833790335645), np.float64(5.741402534298986)]

In [21]:
from scipy.signal import welch
import numpy as np

fs = 128

bands = {
    "delta": (0.5, 4),
    "theta": (4, 8),
    "alpha": (8, 13),
    "beta":  (13, 30),
    "gamma": (30, 45)
}

band_features = []

for ch in eeg:

    freqs, psd = welch(ch, fs=fs)

    for low, high in bands.values():

        idx = (freqs >= low) & (freqs <= high)

        band_power = np.trapezoid(psd[idx], freqs[idx])

        band_features.append(band_power)

print("Number of band features:", len(band_features))
print(band_features[:10])

Number of band features: 160
[np.float64(9.203260169136819), np.float64(7.5893229674803715), np.float64(6.959603085540615), np.float64(13.157610417487241), np.float64(8.382560226118017), np.float64(8.339617256877428), np.float64(7.271636353941981), np.float64(5.462922154266634), np.float64(11.316623352922354), np.float64(6.649390235593953)]

In [22]:
print(dataset_df.shape)
dataset_df.head()

(360, 5)

                           file        task  subject  trial  stress_score
0  Arithmetic_sub_10_trial1.mat  Arithmetic       10      1             3
1  Arithmetic_sub_10_trial2.mat  Arithmetic       10      2             4
2  Arithmetic_sub_10_trial3.mat  Arithmetic       10      3             6
3  Arithmetic_sub_11_trial1.mat  Arithmetic       11      1             7
4  Arithmetic_sub_11_trial2.mat  Arithmetic       11      2             6

In [23]:
from scipy.io import loadmat
from scipy.signal import welch
import numpy as np

fs = 128

bands = {
    "delta": (0.5, 4),
    "theta": (4, 8),
    "alpha": (8, 13),
    "beta":  (13, 30),
    "gamma": (30, 45)
}

def extract_features(eeg):

    features = []

    # Time-domain features
    for ch in eeg:
        features.extend([
            np.mean(ch),
            np.std(ch),
            np.var(ch),
            np.sqrt(np.mean(ch**2))
        ])

    # Frequency-domain features
    for ch in eeg:

        freqs, psd = welch(ch, fs=fs)

        for low, high in bands.values():

            idx = (freqs >= low) & (freqs <= high)

            band_power = np.trapezoid(
                psd[idx],
                freqs[idx]
            )

            features.append(band_power)

    return features

In [24]:
sample_file = files[0]

eeg = loadmat(sample_file)["Clean_data"]

sample_features = extract_features(eeg)

print(len(sample_features))

288

In [25]:
all_features = []

for _, row in dataset_df.iterrows():

    file_path = (
        Path("../../datasets/SAM40/filtered_data")
        / row["file"]
    )

    eeg = loadmat(file_path)["Clean_data"]

    features = extract_features(eeg)

    all_features.append(features)

print("Total recordings:", len(all_features))
print("Features per recording:", len(all_features[0]))

Total recordings: 360
Features per recording: 288

In [26]:
features_df = pd.DataFrame(all_features)

print(features_df.shape)
features_df.head()

(360, 288)

,0,1,2,3,4,5,6,7,8,9,...,278,279,280,281,282,283,284,285,286,287
0,-0.074657,6.740791,45.438258,6.741204,-0.045287,6.253516,39.106461,6.253680,-0.029643,5.741403,...,12.747696,10.737993,8.389438,16.541257,9.383178,25.704150,17.331116,13.121828,23.224801,13.082408
1,0.092489,7.091745,50.292846,7.092348,0.081880,6.224445,38.743720,6.224984,0.153716,6.056759,...,7.756798,10.348464,5.987932,17.758285,14.116481,15.682007,14.457869,9.014670,27.594673,19.482401
2,-0.037182,7.060756,49.854273,7.060854,-0.042347,6.323398,39.985367,6.323540,-0.071464,5.961646,...,9.592608,8.321642,6.703407,17.580674,12.483964,17.913242,14.299978,9.980425,28.898009,18.531803
3,0.060104,7.170137,51.410859,7.170388,0.212066,9.380086,87.986015,9.382483,0.145558,10.360620,...,13.873054,15.000341,15.366263,32.413479,26.908263,29.458650,27.280555,19.433629,47.427225,34.391778
4,0.031028,6.664629,44.417278,6.664701,0.047204,9.337539,87.189636,9.337658,0.104286,9.888134,...,18.705537,15.964376,16.107026,36.995017,28.410412,27.899519,24.152146,22.319953,45.406802,33.285317

In [27]:
final_df = pd.concat(
    [
        features_df.reset_index(drop=True),
        dataset_df[["stress_score"]].reset_index(drop=True)
    ],
    axis=1
)

print(final_df.shape)

final_df.head()

(360, 289)

,0,1,2,3,4,5,6,7,8,9,...,279,280,281,282,283,284,285,286,287,stress_score
0,-0.074657,6.740791,45.438258,6.741204,-0.045287,6.253516,39.106461,6.253680,-0.029643,5.741403,...,10.737993,8.389438,16.541257,9.383178,25.704150,17.331116,13.121828,23.224801,13.082408,3
1,0.092489,7.091745,50.292846,7.092348,0.081880,6.224445,38.743720,6.224984,0.153716,6.056759,...,10.348464,5.987932,17.758285,14.116481,15.682007,14.457869,9.014670,27.594673,19.482401,4
2,-0.037182,7.060756,49.854273,7.060854,-0.042347,6.323398,39.985367,6.323540,-0.071464,5.961646,...,8.321642,6.703407,17.580674,12.483964,17.913242,14.299978,9.980425,28.898009,18.531803,6
3,0.060104,7.170137,51.410859,7.170388,0.212066,9.380086,87.986015,9.382483,0.145558,10.360620,...,15.000341,15.366263,32.413479,26.908263,29.458650,27.280555,19.433629,47.427225,34.391778,7
4,0.031028,6.664629,44.417278,6.664701,0.047204,9.337539,87.189636,9.337658,0.104286,9.888134,...,15.964376,16.107026,36.995017,28.410412,27.899519,24.152146,22.319953,45.406802,33.285317,6

In [28]:
def stress_class(score):
    if score <= 3:
        return "Low"
    elif score <= 6:
        return "Medium"
    else:
        return "High"

final_df["stress_class"] = final_df["stress_score"].apply(stress_class)

print(final_df["stress_class"].value_counts())

stress_class
Medium    188
Low       102
High       70
Name: count, dtype: int64

In [29]:
final_df.to_csv(
    "../../datasets/SAM40/sam40_features.csv",
    index=False
)

print("Saved successfully")

Saved successfully